---
- name: install_metric_beat
  apt:
    deb: https://artifacts.elastic.co/downloads/beats/metricbeat/metricbeat-6.4.0-amd64.deb

- name: copy_metrics_config
  template:
    src: templates/metricbeat.yml.j2
    dest: /etc/metricbeat/metricbeat.yml
    owner: root
    group: root
    mode: 0644

- name: wait_for_elasticsearch
  wait_for:
    port: 9200
    delay: 30
  
- name: wait_for_kibana
  wait_for:
    port: 5601
    delay: 30
    
- name: configure_ship_metrics
  shell: metricbeat modules enable system; metricbeat setup -e

- name: start_metric_beat
  service:
    name: metricbeat
    state: started