---
#- name: install Java8
- include_role: 
    name: common
    tasks_from: java8
- include: elasticsearch.yml
- include: kibana.yml
- include: logstash.yml
- include: beats.yml
- include: elasticsearch_hadoop.yml
